Fixes for synthesis
pulp-platform/pulp_soc pull request #81
Opened 2022-04-22 07:25 UTC by micprog

Two issues cropped up when running through synopsys:
- double assigned signals (grounded `stdout_bus` in `soc_peripherals`) with `TARGET_SYNTHESIS`
- invalid symbol for array interface assignments in gen loop (See also https://github.com/pulp-platform/pulpissimo/issues/332)

2022-04-22 09:02 UTC, meggiman requested changes
Thank's a lot for the PR. I have but a few minor suggestions.

2022-04-22 09:02 UTC, meggiman commented on rtl/pulp_soc/tcdm_demux.sv
> +     XBAR_TCDM_BUS.Master                         slave_ports[NR_OUTPUTS-1:0]
Again. why change the ordering?

2022-04-22 09:12 UTC, micprog commented on rtl/pulp_soc/soc_interconnect.sv
> +    XBAR_TCDM_BUS err_demux_slaves[NR_MASTER_PORTS_INTERLEAVED_ONLY*2-1:0]();
I modified the ordering as this is what is generally used for `logic` arrays, but I agree that this should not be mixed here. I will revert to the 0:max convention.

2022-05-03 18:37 UTC, meggiman commented
lgtm! Thanks a lot.

2022-05-03 18:38 UTC, merged