Michaero/v5.0.0 draft
pulp-platform/pulp_soc pull request #96
Opened 2024-03-05 15:48 UTC by micprog

2024-03-06 11:25 UTC, bluewww commented on Makefile
> +## Regenerate the register file and HAL C-header the soc_ctrl register.
Needs to be a phony target

2024-03-06 11:31 UTC, bluewww requested changes
Changes seem to reasonable. Did we test this PR somewhere in PULPissimo?

2024-03-06 11:32 UTC, bluewww commented
needs a changelog entry

2024-03-14 10:48 UTC, micprog commented on Makefile
> +## Regenerate the register file and HAL C-header the soc_ctrl register.
Done

2024-03-14 12:45 UTC, bluewww approved these changes
Looks good! Let me know once your ready we will remove the `draft` from the PR title and merge.

2024-05-15 10:56 UTC, bluewww commented on rtl/pulp_soc/soc_interconnect.sv
> +      LatencyMode: axi_pkg::MuxAw | axi_pkg::MuxAr | axi_pkg::MuxW,
What does this change?

2024-05-15 11:02 UTC, micprog commented on rtl/pulp_soc/soc_interconnect.sv
> +      LatencyMode: axi_pkg::MuxAw | axi_pkg::MuxAr | axi_pkg::MuxW,
This caused an issue with vivado, related to https://github.com/pulp-platform/axi/pull/340. It does not change the actual configuration.

2024-05-23 13:34 UTC, merged